name: CD Frontend (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Ensure namespace
        run: kubectl create namespace ${{ secrets.K8S_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply frontend manifest
        run: kubectl apply -n ${{ secrets.K8S_NAMESPACE }} -f k8s/frontend.yaml

      - name: Wait for frontend pod Ready
        run: kubectl wait --for=condition=Ready pod -l app=frontend -n ${{ secrets.K8S_NAMESPACE }} --timeout=300s || true

      - name: Show frontend service
        run: kubectl get svc -n ${{ secrets.K8S_NAMESPACE }}
