name: CI - PRs & Pushes

on:
  pull_request:
    branches: [ main, development ]
  push:
    branches:   [ main, development ]
    paths:      [ "backend/**", ".github/workflows/**" ]

jobs:
  run_reusable_ci:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      python-version: "3.10"
