name: Frontend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend_ci.yml"

env:
  # EDIT if your ACR name changes
  ACR_NAME: sit722acr27253
  # Keep tag aligned with your manifests/CD
  IMAGE_TAG: manual

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate AZURE_CREDENTIALS is present
        shell: bash
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "AZURE_CREDENTIALS secret is missing or empty." >&2
            exit 1
          fi

      - name: Azure login (Service Principal JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Resolve ACR login server
        id: acr
        shell: bash
        run: |
          set -e
          ACR_LOGIN_SERVER=$(az acr show -n "$ACR_NAME" --query loginServer -o tsv)
          echo "ACR_LOGIN_SERVER=$ACR_LOGIN_SERVER" | tee -a "$GITHUB_ENV"
          echo "Using ACR: $ACR_LOGIN_SERVER"

      - name: Login to Azure Container Registry
        run: az acr login --name "$ACR_NAME"

      - name: Build and Push Frontend Image
        shell: bash
        run: |
          set -e
          docker build -t "$ACR_LOGIN_SERVER/frontend:${IMAGE_TAG}" ./frontend
          docker push "$ACR_LOGIN_SERVER/frontend:${IMAGE_TAG}"

      - name: Logout from Azure
        if: always()
        run: az logout
