name: Release Orchestration (CI → CD)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (e.g., prod, staging)"
        required: true
        default: "prod"

jobs:
  backend:
    uses: ./.github/workflows/cd_backend.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
