name: CI - Test, Build & Push (Monorepo)

on:
  push:
    branches: [ develop, main ]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ develop ]
    paths:
      - "backend/**"
      - "frontend/**"

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  TAG: 1.0.0
# 
jobs:
  test_and_build:
    runs-on: ubuntu-latest

    services:
      product_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: products
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s --health-timeout 5s --health-retries 5

      order_db:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: orders
        ports: [ "5433:5432" ]
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/product_service/requirements.txt
          pip install -r backend/order_service/requirements.txt
          pip install pytest httpx

      - name: Run tests - product_service
        working-directory: backend/product_service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: products
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: pytest -q

      - name: Run tests - order_service
        working-directory: backend/order_service
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5433
          POSTGRES_DB: orders
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        run: pytest -q

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Derive ACR name
        id: acr
        run: |
          ACR_NAME=$(echo "${{ env.ACR_LOGIN_SERVER }}" | cut -d. -f1)
          echo "name=$ACR_NAME" >> $GITHUB_OUTPUT

      - name: ACR login
        run: az acr login -n ${{ steps.acr.outputs.name }}

      - name: Build & push product image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/product:${{ env.TAG }} backend/product_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/product:${{ env.TAG }}

      - name: Build & push order image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/order:${{ env.TAG }} backend/order_service
          docker push ${{ env.ACR_LOGIN_SERVER }}/order:${{ env.TAG }}

      - name: Build & push frontend image
        run: |
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.TAG }} frontend
          docker push ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.TAG }}

  trigger_release_on_main:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ test_and_build ]
    uses: ./.github/workflows/release.yml
    with:
      environment: prod
    secrets: inherit
