name: CI

on:
  pull_request:
    branches: [ main, development ]
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/**"
  push:
    branches: [ development ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Enable Corepack & pin pnpm
        run: |
          corepack enable
          # Use the version from package.json if present; otherwise fall back to latest.
          if jq -e '.packageManager' package.json >/dev/null 2>&1; then
            VER="$(jq -r '.packageManager' package.json | sed -n 's/.*pnpm@\([0-9][0-9.]*\).*/\1/p')"
            corepack prepare "pnpm@${VER}" --activate
          else
            corepack prepare pnpm@latest --activate
          fi

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run tests
        env:
          CI: "true"
        run: pnpm test -- --ci

      - name: Upload coverage (if present)
        if: ${{ always() && hashFiles('coverage/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.node }}
          path: coverage/**
          if-no-files-found: ignore
